### ISSUE TITLE
Move content-type negotiation out of the Controller into an HTTP component

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#1305]
Major issue for doing this is probably, that the supported content-types are supposed to be configured per Controller via `$supportedMediaTypes` property.

See #550

**Comment by albe** [comment]
@bwaidelich is this even doable/feasible then? It would require to change this way of defining the supported media types to Settings or a static variable, and even then it would only be possible *after* Routing. Plus, it needs to set the `format` of the **Action**Request, which is only available after the Dispatching component (or the component that creates the ActionRequest, which could be extracted).

**Comment by bwaidelich** [comment]
IMO it should happen between routing and dispatching..
In the long run `AbstractController::$supportedMediaTypes` should be moved. To the routes for example:

```yaml
-
  uriPattern: 'some/path'
  defaults:
    '@package':    'Acme.Demo'
    '@controller': 'Standard'
    '@action':     'someAction'
  httpMethods: ['GET']
  acceptedMediaTypes: ['text/html', 'application/json']
```

In any case, [this part](https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/Controller/AbstractController.php#L126-L128) should be removed – it alters the ActionRequest during controller initialization 😱

For a start everything could be done in the `DispatchComponent` I assume. Or in a new `ActionRequestFactoryComponent` (see https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/DispatchComponent.php#L86)

**Comment by albe** [comment]
I like the configuration via Routes, but how would you make that possible to set in a hierarchy? Subroutes?

**Comment by bwaidelich** [comment]
> how would you make that possible to set in a hierarchy? 

A hierarchy of what?
I would expect it to work just like `httpMethods` for example: You can set it in main routes and override it in sub routes.
Also, we could support the common patterns (`text/*` matches all text types, ...). By default `*/*` could be assumed.

At this point we could also evaluate `AbstractController::supportedMediaTypes` for B/C

**Comment by albe** [comment]
Hierarchy of the routes that all accept a specific set of content-types, e.g.
``` 
/foo/x/({@action}/)
/foo/({@action}/)
/bar/baz/({@action}/)
etc.
```

So if I understand correctly, that would be solved with (Nested) SubRoutes like this:

```
-
  uriPattern: '<SubRoutes>'
  defaults:
    '@package':    'Acme.Demo'
  acceptedMediaTypes: ['text/html', 'application/json']
  subRoutes:
    'SubRoutes':
      package: 'Acme.Demo'
      (suffix:  'FooBar')
```

> Also, we could support the common patterns (text/* matches all text types, ...). By default */* could be assumed.

Hm, but what if the Controller can't map the resolved format to a proper View?

> At this point we could also evaluate AbstractController::supportedMediaTypes for B/C

So the component would need to create an instance of the Controller early on and read out the $supportedMediaTypes - or maybe this can be done with (cached) reflection.

**Comment by albe** [comment]
little update - currently the `ActionRequest` is created inside the `PrepareMvcRequestComponent`, so content type negotiation for the controller could be moved there (or in a component after that)

**Comment by albe** [comment]
> In any case, this part should be removed – it alters the ActionRequest during controller initialization 😱

So this is still an issue to date, since the `beforeControllerInvocation($actionRequest, $actionResponse, $controller)` signal is emitted before the content-type negotiation. An intermediate easy step could be to move the negotiation to between that and the insanciation of the controller.

Regarding the routes setting - that would **imply** that the route resolving depends on the supported content-type, i.e. you could have:

```yml
-
  uriPattern: 'some/path'
  defaults:
    '@package':    'Acme.Demo'
    '@controller': 'Standard'
    '@action':     'someAction'
  httpMethods: ['GET']
  acceptedMediaTypes: ['text/html']

-
  uriPattern: 'some/path'
  defaults:
    '@package':    'Acme.Demo'
    '@controller': 'Standard'
    '@action':     'someJsonAction'
  httpMethods: ['GET']
  acceptedMediaTypes: ['application/json']
```

which would be a nice feature, no question. We'd need to negotiate during routing then and what if two routes would accept a request that accepts multiple content-types that are split among routes, e.g. has `Accept: text/html; application/json` in the above case? Route to the first `Accept`?

>  Plus, it needs to set the format of the ActionRequest, which is only available after the Dispatching component

See also #2005

**Comment by bwaidelich** [comment]
> [...] what if two routes would accept a request that accepts multiple content-types
> [...] Route to the first Accept?

Yes, first matching route wins, I'd say.
In the meantime I'm not sure if a new option like this makes sense though. It would mean that the accept header needs to be part of the Routing Parameters (in order to create a separate caching partition)..

Instead I could imagine some generic `handler` to be configured for each Route, that has access to the parameters like:

```yaml
-
  uriPattern: 'some/path'
  // ...
  handler: 'Some/Custom/AcceptMediaTypeHandler'
  handlerOptions:
    acceptedMediaTypes: ['text/html']
```

(or similar)

**Comment by albe** [comment]
> in order to create a separate caching partition

Didn't even think of this and yes, that's a total **blocker**! By the immense amount of different combinations of accept headers, this would just explode the cache.

> Update: "Filters" might be a better concept..

Hmm... but that would need to run *after* resolving (from cache), so it would need to load the routing configuration even on cache hit. Or, the configured accepted media types (or generally filter options) are stored in the (cached) `$matchResult`?

**Comment by sorenmalling** [comment]
Start by fetching lowest possible when resolving: Get path that matches. Get path with media type match?

> Instead I could imagine some generic handler to be configured for each Route, that has access to the parameters like:

Can we avoid "requiring" others to write handlers and introduce it in the core? or is that already the idea of this?

**Comment by bwaidelich** [comment]
> but that would need to run after resolving (from cache)

I imagined it to work like this:
A new HTTP component (i.e. middleware) that detects the `Accept` header and registers it a corresponding `RouteParameter` (not accepting all combinations of course)..
Something like this:

```yaml
Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            'Wwwision.Test:ServerSent':
              position: 'before routing'
              component: 'Wwwision\Test\Http\DetectMediaTypeComponent'
              componentOptions:
                'supportedMediaTypes': ['text/html', 'application/json']
```

```php
final class DetectMediaTypeComponent implements ComponentInterface
{

    /** @var string[] */
    private $supportedMediaTypes;

    public function __construct(array $options = [])
    {
        $this->supportedMediaTypes = $options['supportedMediaTypes'] ?? [];
    }

    public function handle(ComponentContext $componentContext)
    {
        /** @var RouteParameters $routeParameters */
        $routeParameters = $componentContext->getParameter(RoutingComponent::class, 'parameters') ?? RouteParameters::createEmpty();

        $mediaType = MediaTypeHelper::negotiateMediaType(MediaTypeHelper::determineAcceptedMediaTypes($componentContext->getHttpRequest()), $this->supportedMediaTypes);
        $routeParameters = $routeParameters->withParameter('mediaType', $mediaType);
        $componentContext->setParameter(RoutingComponent::class, 'parameters', $routeParameters);
    }
}
```

In a custom RoutePart handler you could already access those parameters like

```php
    protected function matchValue($value)
    {
        $mediaType = $this->parameters->getValue('mediaType') ?? 'text/html';
        return new MatchResult(MediaTypes::getFilenameExtensionFromMediaType($mediaType));
    }
```

> Can we avoid "requiring" others to write handlers and introduce it in the core?

I don't know.. Personally I would never use this kind of automatism and it introduces additional complexity and a (slight) performance hit.
I would rather prefer some good documentation and/or a separate package so that people can opt in.

But I'm not very clear about the actual use cases to be honest.. Switching a view implementation based on the `Accept` header, is that still a common scenario? Or what do you guys need this for?
