### ISSUE TITLE
Requesthandler should support json array without object wrapper

### ISSUE THREAD

**Issue by mwitte** [neos/flow-development-collection#1554]
### Description

It should be possible to send a json array without object wrapper to a controller action with Content-Type `json/application`

### Steps to Reproduce
`curl --header "Content-Type: application/json" --request POST --data '[{"foo":"bar"},{"bar":"foo"}]' https://myhost/myroute`

#### Expected behavior
There should be the possibility to define a name for this special case in the route. 

#### Actual behavior

```
Neos\Flow\Mvc\Exception\InvalidArgumentNameException:
Invalid argument name (must be a non-empty string). 1210858767
Neos\Flow\Mvc\ActionRequest_Original::setArgument("0", array|1|)
```

Flow wants to map the element keys as request arguments which makes no sense here. The array should be mapped to an argument name which should be configurable in the route.
### Affected Versions
All versions

**Comment by albe** [comment]
This would indeed be helpful for building e.g. an API endpoint receiving multiple entities and avoiding the currently necessary wrapping of request body in an object (i.e. `--data '{ "foos": [{"foo":"bar"}, {"bar":"foo"}] }'`)

The place to hook into would be here:
https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Mvc/DispatchComponent.php#L102

Could look something like this:
```php
$bodyArgumentName = $componentContext->getParameter(Routing\RoutingComponent::class, 'bodyArgumentName');
if ($bodyArgumentName !== null) {
    $arguments = Arrays::arrayMergeRecursiveOverrule($arguments, [$bodyArgumentName => $parsedBody]);
} else {
    $arguments = Arrays::arrayMergeRecursiveOverrule($arguments, $parsedBody);
}
```

Routes.yaml:
```yaml
-
  name: 'my multi value receiving endpoint'
  uriPattern: '/foo/bar'
  defaults:
    '@controller': 'Foo'
    '@action':     'bar'
    '@format':     'json'
  httpMethods: ['POST']
  bodyArgumentName: 'foos'
```

wdyt @bwaidelich ?
