### ISSUE TITLE
Overwrite Doctrine mappingTypes

### ISSUE THREAD

**Issue by MaxRuediger** [neos/flow-development-collection#1703]
We have users in multiple time zones. So, we need to save the DateTime object in database using the UTC timezone. For that, I tried to do this:

https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/working-with-datetime.html#handling-different-timezones-with-the-datetime-type

I want to avoid to change the DateTime type from ```@var DateTime``` to something other like 
```
@var DateTime
@ORM\Column(type="UTCDateTime")
```

To overwrite a type (like suggested in the doctrine doc), we should add an "overwrite" flag or something like that to the mappingTypes, e.g in settings.yaml:

```
doctrine:
  dbal:
    mappingTypes:
      'datetime':
        dbType: 'datetime'
        className: 'Acme\Demo\Doctrine\DataTypes\UTCDateTimeType'
        overwrite: true
```

And we need to modify the following to EntityManagerConfiguration.php at enhanceEntityManager.php:

```
if (!Type::hasType($typeName)) {
  Type::addType($typeName, $typeConfiguration['className']);
} else if ($typeConfiguration['overwrite']) {
  Type::overrideType($typeName, $typeConfiguration['className']);
}
```

What do you think?

### Affected Versions
Flow: 5.1.10
