### ISSUE TITLE
Authentication Redirect with subfolder fails

### ISSUE THREAD

**Issue by kaystrobach** [neos/flow-development-collection#1797]
### Description

instead of redirecting to `/t/package/authentication/index` flow 4.3.18+ redirects to ``/t/t/package/authentication/index`

### Steps to Reproduce

1. flow in subfolder (symlink)
2. enable rewrite
3. 

#### Expected behavior

same as 4.3.17 redirect to the correct auth endpoint

#### Actual behavior

s.a.

### Affected Versions

Flow:

* atleast 4.3.18 - 4.3.21

**Comment by albe** [comment]
Probably a regression from https://github.com/neos/flow-development-collection/pull/1682/files#diff-d9281be63867d9c5a9b3d0fce5380ee5R67?

**Comment by kaystrobach** [comment]
Any idea how to help to fix this problem? I’m not so much into the routing component.

**Comment by albe** [comment]
Best thing would be to have just a simple test case that fails with 4.3.18 and is green with 4.3.17. Afterwards the change could be adjusted to cover the new "fixed" behaviour and still work as before without regression.

**Comment by kaystrobach** [comment]
what do you need to reproduce?

basicly i just added the .htaccess to rewrite with a subdirectory.

**Comment by kaystrobach** [comment]
problem is, that i need to understand that part preciscly to add more valuable information.

**Comment by kaystrobach** [comment]
As far as i can see the redirect is triggered here:

`Packages/Framework/Neos.Flow/Classes/Security/Authentication/EntryPoint/WebRedirect.php:50`

```php
            $actionName = $this->extractRouteValue($routeValues, '@action');
            $controllerName = $this->extractRouteValue($routeValues, '@controller');
            $packageKey = $this->extractRouteValue($routeValues, '@package');
            $subPackageKey = $this->extractRouteValue($routeValues, '@subpackage');
            $uri = $this->uriBuilder->setCreateAbsoluteUri(true)->uriFor($actionName, $routeValues, $controllerName, $packageKey, $subPackageKey);
```

The code should always return an absolute URI, das the function `setCreateAbsolute` is called with the parameter `true`.

Out Settings for the Authentication Provider look like:

`Settings.yaml`

```yaml
Neos:
  Flow:
    security:
      enable: true
      authorization: null
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: WebRedirect
            entryPointOptions:
              uri: Vendor.Package/Login/index
              routeValues:
                '@package': Vendor.Package
                '@controller': Login
                '@action': index
```

The uri part can be safely removed, as the first condition matches `true` on `routeValues`.

Our directory structure looks like this:

```
/
/testing    --> symlink to flow framework deployed with typo3.surf
/testing/index.php
```

`.htaccess`

```
        # Enable URL rewriting
        RewriteEngine On

        # Set flag so we know URL rewriting is available
        SetEnv FLOW_REWRITEURLS 1

        # You will have to change the path in the following option if you
        # experience problems while your installation is located in a subdirectory
        # of the website root.
        RewriteBase /testing/
 SetEnv FLOW_CONTEXT Production/Testing

        # Stop rewrite processing no matter if a package resource, robots.txt etc. exists or not
        RewriteRule ^(_Resources/Packages/|robots\.txt|favicon\.ico) - [L]

        # Stop rewrite process if the path points to a static file anyway
        RewriteCond %{REQUEST_FILENAME} -f [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule .* - [L]

        # Perform rewriting of persistent private resources
        RewriteRule ^(_Resources/Persistent/[a-z0-9]+/(.+/)?[a-f0-9]{40})/.+(\..+) $1$3 [L]

        # Perform rewriting of persitent resource files
        RewriteRule ^(_Resources/Persistent/.{40})/.+(\..+) $1$2 [L]

        # Make sure that not existing resources don't execute TYPO3 Flow
        RewriteRule ^_Resources/.* - [L]

        # Continue only if the file/symlink/directory does not exist
        RewriteRule (.*) index.php
```
