### ISSUE TITLE
Allow Authentication forward instead of redirect

### ISSUE THREAD

**Issue by kaystrobach** [neos/flow-development-collection#1885]
### Description

```yaml
security:
  authentication:
    providers:
      DefaultProvider:
        provider: PersistedUsernamePasswordProvider
        entryPoint: 'WebRedirect'
        entryPointOptions:
          routeValues:
            '@package': 'Your.Package'
            '@controller': 'Authenticate'
            '@action': 'login'
```

With that config we can redirect any failed login to a different location.
Problem with that is, that this is an additional roundtrip.

`\Neos\Flow\Security\Authentication\EntryPoint\WebRedirect`

### Steps to Reproduce

1. use security framework

#### Expected behavior

1. allow to internally forward to another action instead of doing a redirect

#### Actual behavior

redirect

### Affected Versions

Flow: 0-6

You can get this information by running `composer show`.
