### ISSUE TITLE
Feature: Allow for easy overriding of extracting credentials in UsernamePassword token

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#1944]
When implementing own username/password token based authentication, I have different naming of fields or requirements for arguments. This causes me to reimplement (copy/paste) large parts of the UsernamePassword token, since the attributes are hardcoded inside the updateCredentials method.

The extracting of credentials could be moved to a separate method, that can then be overridden by a own implementation

**Comment by DavidSporer** [comment]
I'm not sure if this is the right place but I just noticed another issue that might be related to that:
When you want to use the same authentication provider for regular authentication with a login form and also use that for Basic Auth then the regular WebRedirect won't work since Basic Auth should return the WWW-Authenticate basic header.
Is this the right place to ask or has someone solved such an issue already?

**Comment by albe** [comment]
@bwaidelich any idea on what David said? I have no clue t.b.h.

**Comment by bwaidelich** [comment]
@DavidSporer @albe that's another (IMO unrelated) issue that EntryPoints are always evaluated so you need two provider configurations in that case. It would be nice to be able to use the "request patterns" for those, too, like:
```yaml
security:
  authentication:
    providers:
      DefaultProvider:
        provider: PersistedUsernamePasswordProvider
        entryPoint: 'WebRedirect'
        entryPointOptions: # ...
        filters:
          'Some.Package:CustomPattern':
            pattern:  'Acme\MyPackage\Security\MyOwnRequestPattern'
            patternOptions: # ...
```

I thought there was already a ticket for that, but I can't find it.. Would you create a new one?
