### ISSUE TITLE
Wrong place for throwables to configure the FileStorage

### ISSUE THREAD

**Issue by markusguenther** [neos/flow-development-collection#2082]
### Description

First at all I planned to disable the Exception file logging and use my sentry logs only.
So I stumbled upon a bug.

**The default configuration says:**

```yaml
Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          throwables:
            storageClass: Neos\Flow\Log\ThrowableStorage\FileStorage
            optionsByImplementation:
              'Neos\Flow\Log\ThrowableStorage\FileStorage':
                storagePath: '%FLOW_PATH_DATA%Logs/Exceptions'
```

So I tried to send the storagePath to something like /tmp but as this did not worked I checked the flow code and in the initializeExceptionStorage of the Core we expect the config to be at

```yaml
Neos:
  Flow:
    log:
      throwables:
        storageClass: Neos\Flow\Log\ThrowableStorage\FileStorage
         optionsByImplementation:
          'Neos\Flow\Log\ThrowableStorage\FileStorage':
            storagePath: '%FLOW_PATH_DATA%Logs/Exceptions'
```

### Steps to Reproduce

1. Change the default storagePath
2. Throw an exception
3. Exception file will be still at the default place

#### Expected behavior

Exceptions will be written to the defined place.

#### Actual behavior

Always are at the default place because the else branch will be never using the configured value.

### Affected Versions

Neos: 5.0 and later

Flow: 6.0 and later
