### ISSUE TITLE
Make injecting the framework loggers more straightforward and document it

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2125]
With the PSR-3 change, getting a hold of the system logger / security logger has changed and (deprecated) interfaces for b/c have been introduced:

```yml
# Deprecated as of Flow 6.0, you should inject Psr\Log\LoggerInterface
# or use the factory to get the "systemLogger"
Neos\Flow\Log\PsrSystemLoggerInterface:
  scope: singleton
  factoryObjectName: Neos\Flow\Log\PsrLoggerFactoryInterface
  factoryMethodName: get
  arguments:
    1:
      value: systemLogger
```

So, right now, the correct way to get the SystemLogger is:
```
@Flow\Inject
@var \Psr\Log\LoggerInterface
```
And for the security logger, you have to inject the `Neos\Flow\Log\PsrLoggerFactoryInterface` and manually fetch the logger with `->get('securityLogger')`, which is more than suboptimal.

However, virtual objects (#1964)  are a thing now and we have all the tools to make this more straightforward:
```yml
'Neos.Flow:SystemLogger':
  className: Psr\Log\LoggerInterface
  scope: singleton
  factoryObjectName: Neos\Flow\Log\PsrLoggerFactoryInterface
  factoryMethodName: get
  arguments:
    1:
      value: systemLogger

'Neos.Flow:SecurityLogger':
  className: Psr\Log\LoggerInterface
  scope: singleton
  factoryObjectName: Neos\Flow\Log\PsrLoggerFactoryInterface
  factoryMethodName: get
  arguments:
    1:
      value: securityLogger
```
should be added to the `Objects.yaml` configuration and documented on how to inject those:
```php
/**
 * @Flow\Inject(name="Neos.Flow:SystemLogger")
 * @var LoggerInterface
 */
protected $systemLogger;

/**
 * @Flow\Inject(name="Neos.Flow:SecurityLogger")
 * @var LoggerInterface
 */
protected $securityLogger;
```
