### ISSUE TITLE
Replace routing variables in RoutePart handler options

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#2142]
### Description

variables in `Routes.yaml` allow custom placeholders to be defined in a central place.
For example a `Routes.yaml`

```yaml
-
  name: 'Some Route with suffix <suffix>'
  uriPattern: 'foo/bar<suffix>'
  defaults:
    'suffix': '<suffix>'
    # ...
```
and a corresponding `Settings.yaml` of
```yaml
Neos:
  Flow:
    mvc:
      routes:
        'Some.Package':
          suffix: '.html'
```

will be merged to an effective route configuration of
```yaml
-
  name: 'Some Route with suffix .html'
  uriPattern: 'foo/bar.html'
  defaults:
    'suffix': '.html'
    # ...
```
(see https://flowframework.readthedocs.io/en/6.3/TheDefinitiveGuide/PartIII/Routing.html#nested-subroutes for more examples)

However, those placeholders are currently _not_ replaced in route part handler options. But this would be useful for example in order to solve https://github.com/neos/neos-development-collection/issues/3020

**Comment by bwaidelich** [comment]
**Note:** With #2155 variables will be replaces in _all_ route configuration options so you could in theory do:

```yaml
-
  uriPattern: '{foo}'
  routeParts:
    'foo':
      handler: '<handler>'
```
