### ISSUE TITLE
TypeError exception in Neos\Cache\Backend\MemcachedBackend

### ISSUE THREAD

**Issue by dogawaf** [neos/flow-development-collection#2194]
### Steps to Reproduce

I configured some caches to use Memcached as backend:

```
Flow_Mvc_Routing_Route:
  backend: Neos\Cache\Backend\MemcachedBackend
  backendOptions:
    servers:
      - 127.0.0.1

Flow_Mvc_Routing_Resolve:
  backend: Neos\Cache\Backend\MemcachedBackend
  backendOptions:
    servers:
      - 127.0.0.1

Neos_Fusion_Content:
  backend: Neos\Cache\Backend\MemcachedBackend
  backendOptions:
    servers:
      - 127.0.0.1

Neos_Neos_Fusion:
  backend: Neos\Cache\Backend\MemcachedBackend
  backendOptions:
    servers:
      - 127.0.0.1

```

I flushed the cache, and went to the Neos login page. The following exception was thrown:

<img width="1363" alt="Capture d’écran 2020-10-29 à 19 05 03" src="https://user-images.githubusercontent.com/381969/97614126-d8e01200-1a19-11eb-99fb-92a8919bddc7.png">

#### Expected behavior

The Neos backend should display correctly after the cache was cleared.

#### Actual behavior

The Neos backend displays an exception after the cache was cleared.

### Affected Versions

Neos 5.3.0 + Flow 6.3.1
