### ISSUE TITLE
Multiple Policy.yaml role merging is broken

### ISSUE THREAD

**Issue by Pingu501** [neos/flow-development-collection#2341]
### Description

As Flow supports splitting of your `Policy.yaml` I wanted to use it and split Policys by parts of the application. After a couple of ours of really strange behaviour I could isolate the problem. The merging of the `roles` inside a package seams to be more like an override

### Steps to Reproduce

1. Inside your SitePackage, create `Configuration/Policy.Bar.yaml` and fill it with

```
privilegeTargets:
  'Neos\Flow\Security\Authorization\Privilege\Method\MethodPrivilege':
    'Sandstorm.ProjectX:MyController':
      matcher: 'method(Sandstorm\ProjectX\Controller\Module\MyController->(?!initialize).*Action())'

roles:
  'Neos.Neos:Administrator':
    privileges:
      -
        privilegeTarget: 'Sandstorm.ProjectX:MyController'
        permission: GRANT
```

2. Inside your SitePackage, create `Configuration/Policy.Foo.yaml` and fill it with

```
privilegeTargets:
  'Neos\Neos\Security\Authorization\Privilege\NodeTreePrivilege':
    'Sandstorm.ProjectX:Neos.All':
      matcher: 'TRUE'

roles:
  'Neos.Neos:Administrator':
    privileges:
      -
        privilegeTarget: 'Sandstorm.ProjectX:Neos.All'
        permission: GRANT
```

3. run `./flow configuration:show --type Policy`

#### Expected behavior

I would expect the `Neos.Neos:Administrator` role to contain the following entries (plus the defaults from Neos)

```
roles:
  'Neos.Neos:Administrator':
    privileges:
      -
         privilegeTarget: 'Sandstorm.ProjectX:MyController'
         permission: GRANT
      -
         privilegeTarget: 'Sandstorm.ProjectX:Neos.All'
         permission: GRANT
    # plus configuration from other packages
```

#### Actual behavior

Only the privileges from the last `Policy.*.yaml` inside the site package made it into the configuration

```
  'Neos.Neos:Administrator':
    privileges:
      -
         privilegeTarget: 'Sandstorm.ProjectX:Neos.All'
         permission: GRANT
    # plus configuration from other packages
```

### Affected Versions

Neos: 5.3.0

Flow: 6.3.4

**Comment by albe** [comment]
The problem is, that we do overwrite numeric indexes when merging the configurations and that's also documented as such in `Arrays::arrayMergeRecursiveOverrule`:
> Merges two arrays recursively and "binary safe" (integer keys are overridden as well)

So while I see this as buggy behaviour in the specific case of having privilege lists in different policies and expecting them to be joined together, this will not be trivial to fix b/c.

For now, a workaround could be to index the privileges with unique names like so:
```
privilegeTargets:
  'Neos\Flow\Security\Authorization\Privilege\Method\MethodPrivilege':
    'Sandstorm.ProjectX:MyController':
      matcher: 'method(Sandstorm\ProjectX\Controller\Module\MyController->(?!initialize).*Action())'

roles:
  'Neos.Neos:Administrator':
    privileges:
      'Sandstorm.ProjectX:MyController':
        privilegeTarget: 'Sandstorm.ProjectX:MyController'
        permission: GRANT
```

```
privilegeTargets:
  'Neos\Neos\Security\Authorization\Privilege\NodeTreePrivilege':
    'Sandstorm.ProjectX:Neos.All':
      matcher: 'TRUE'

roles:
  'Neos.Neos:Administrator':
    privileges:
      'Sandstorm.ProjectX:Neos.All':
        privilegeTarget: 'Sandstorm.ProjectX:Neos.All'
        permission: GRANT
```

should lead to:
```
roles:
  'Neos.Neos:Administrator':
    privileges:
      'Sandstorm.ProjectX:MyController':
         privilegeTarget: 'Sandstorm.ProjectX:MyController'
         permission: GRANT
      'Sandstorm.ProjectX:Neos.All':
         privilegeTarget: 'Sandstorm.ProjectX:Neos.All'
         permission: GRANT
    # plus configuration from other packages
```
