### ISSUE TITLE
Already excisting session containing a token, blocks SecurityContext::getAuthenticationTokens from returning tokens from Settings.yaml

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#2355]
I'm describing this issue here, for a perhaps a pointer on a topic we can revisit or document at one point.

I had a session, containing a auth token `Neos\Flow\Security\Authentication\Token\UsernamePassword`. While I had this session, I was not able to authenticate with my new registered provider in Settings.yaml, registered as such

```
Neos:
  Flow:
    security:
      authentication:
        providers:
          EmailAddressPassword:
            provider: PersistedUsernamePasswordProvider
            token: 'UsernamePassword'
            tokenOptions:
              usernamePostField: 'emailAddress'
              passwordPostField: 'password'
            requestPatterns:
              'SikkerFaktura.Application:AllControllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'SikkerFaktura\Application\Controller\.*'
            entryPoint: WebRedirect
            entryPointOptions:
              routeValues:
                '@package': SikkerFaktura.Login
                '@controller': Login
                '@action': login
                '@format': html
```

From the `AuthenticationProviderManager::authenticate` method, the call to `$tokens = $this->securityContext->getAuthenticationTokens();` returned a empty array.

This lead to my Security log being filled with lines like this

```
20-12-15 11:31:38 9113       127.0.0.1      DEBUG     Neos.Flow            Session 1pJykuMmkRMrpynUiG2mqsmmGBN9A0Vw contains auth token Neos\Flow\Security\Authentication\Token\UsernamePassword for provider EmailAddressPassword. Status: no credentials given
```

and not untill i ran `./flow session:destroyAll`,  i was able to authenticate, and getting the successful lines in to the log

```
20-12-15 11:31:54 9113       127.0.0.1      NOTICE    Neos.Flow            Successfully authenticated token: Username: "soren+test@meteko.dk"
20-12-15 11:31:54 9113       127.0.0.1      DEBUG     Neos.Flow            Session vWHz9bWmkhweZPJZfocmYFgy4XpjNZvF contains auth token Neos\Flow\Security\Authentication\Token\UsernamePassword for provider EmailAddressPassword. Status: authentication successful
```

The first (conflicting) session was created from a Form finisher, that authenticates a new user, with code like this

```
$authenticationTokens = $this->authenticationManager->getSecurityContext()->getAuthenticationTokensOfType(UsernamePassword::class);
            if (count($authenticationTokens) === 1) {
                $authenticationTokens[0]->setAccount($user->getAccount());
                $authenticationTokens[0]->setAuthenticationStatus(TokenInterface::AUTHENTICATION_SUCCESSFUL);
                $this->authenticationManager->authenticate();
            }
```

I have a idea of the SessionDataContainer held a number of serialized properties, that somehow blocks the findings of tokens and/or configuration, added afterwards a once authenticated request.

Is this a topic to address in terms of documentation of authentication and authorization or a technical issue, that we should address in the handling of sessions and tokens?

Please address any known issues, concerns and reason for why it is as it is, and where it should go
