### ISSUE TITLE
Make Welcome package independent of Fluid

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2380]
Currently the flow base distribution still includes Fluid via the Welcome package. That view does not contain a lot of logic so we could easily replace that with a simple view.

**Comment by sorenmalling** [comment]
We already have the `SimpleTemplateView` and, if I'm not wrong, if fluid as removed, the fallback to SimpleTemplateView would still render as expected, if we set the `templatePathAndFilename` option to the excisting file

**Comment by sorenmalling** [comment]
Did a quick test with a `Views.yaml` like this

```
-
  requestFilter: 'isPackage("Neos.Welcome")'
  viewObjectName: '\Neos\Flow\Mvc\View\SimpleTemplateView'
  options:
    templatePathAndFilename: resource://Neos.Welcome/Private/Templates/Standard/Index.html
```

But we do have some conditions in the view and resolving of a resource (CSS) that we will have to address
