### ISSUE TITLE
Switch GH actions to use composer-install action

### ISSUE THREAD

**Issue by albe** [neos/flow-development-collection#2408]
As of https://github.com/ramsey/composer-install/pull/93 a working-directory can be specified and we can use this action to install packages with caching and support for the dependency 'lowest', 'highest' and 'locked' settings.

Replace

```yaml
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/composer
            ${{ env.FLOW_DIST_FOLDER }}/Packages
          key: php-${{ matrix.php-versions }}-${{ matrix.dependencies }}${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php-versions }}-${{ matrix.dependencies }}

      - name: Install dependencies
        run: |
          composer ${{ matrix.dependencies == 'locked' && 'install' || 'update' }} --no-progress --no-interaction ${{ matrix.dependencies == 'lowest' && '--prefer-lowest' || '' }} ${{ matrix.composer-arguments }}
```
with
```yaml
    - name: Install dependencies
      uses: ramsey/composer-install@v1
      with:
        dependency-versions: ${{ matrix.dependencies }}
        composer-options: ${{ matrix.composer-arguments }}
        working-directory: ${{ env.FLOW_DIST_FOLDER }}
```
