### ISSUE TITLE
Possible race condition in VariableFrontend.get()

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#2672]
### Description

When the same session is used concurrently, sometimes the session seemingly ends.

The log then shows an exception about `unserialize()` not being able to process the value retrieved from the cache backend in https://github.com/neos/flow-development-collection/blob/cb92ea7f5e979647277a8111aec4b3cfbccf144f/Neos.Cache/Classes/Frontend/VariableFrontend.php#L94

The reason in this case is an incomplete data file when using the `FileBackend` (other backends are probably not affected.)

### Affected Versions

Flow: 6.3+

**Comment by kitsunet** [comment]
which is weird? because our cache writes should be atomic I thought

**Comment by kdambekalns** [comment]
A possible way to fix this would be

```php
 try {
    return ($this->useIgBinary === true) ? igbinary_unserialize($rawResult) : unserialize($rawResult);
} catch (\Exception $e) {
    // ignore and try again - serialized value might be incomplete and is "fixed" by reading again
}
```

The question is – try once, try multiple times? Slow down between tries, using exponential backoff?

**Comment by robertlemke** [comment]
I'm not sure if this is actually related, but by coincident I experienced a few cache-related errors here locally, while developing an application based on Flow 6.3.14.

Randomly (every xth request) I get an error like the following:

```
The cache file "/application/Data/Temporary/Development/SubContextBeach/SubContextInstance/Cache/Data/Flow_Reflection_Status/Neos_Flow_Mvc_Controller_ActionController" could not be written.
Type: Neos\Cache\Exception
  Code: 1334756737
  File:
Packages/Libraries/neos/cache/Classes/Backend/SimpleFileBackend.php
  Line: 168

  Type: Neos\Flow\Core\Booting\Exception\SubProcessException
  Code: 1355480641
  File: Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
  Line: 704
```

Really not sure if this is related, but wanted to mention it anyway.
