### ISSUE TITLE
Bug: Custom error view ignore `viewOptions` key that is `null`

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#2738]
### Description

some times one wants to unset, by another package inherited option like in `Neos.Neos` (https://github.com/neos/neos-development-collection/pull/3637):

```yaml
options:
  viewClassName: \Neos\Neos\View\FusionExceptionView
  viewOptions:
    templatePathAndFilename: ~
```

but this will be trying to set `'templatePathAndFilename' => null` as option on the `FusionExceptionView`, which doesnt exist - so we need to filter out all `null` options.

### Steps to Reproduce

add to a working error view config this:

```yaml
options:
  viewOptions:
    blaBliBlub: ~
```

#### Expected behavior

expect `blaBliBlub` to be ignored.

#### Actual behavior

`The view options "blaBliBlub" you're trying to set don't exist in class "YourViewClass".`
