### ISSUE TITLE
FEATURE: Add support for secrets stored in a file for the configuration

### ISSUE THREAD

**Issue by erkenes** [neos/flow-development-collection#2935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The configration files already accepts environment variables but it would be helpful if we also can use sensitive data that was stored in a file in example in a [Docker Secret](https://docs.docker.com/engine/swarm/secrets/).

### Possible Solution

A solution could  be something like this:

```yaml
# Settings.yaml

Neos:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: '%file:/run/secrets/db_dbname%'
        user: '%file:/run/secrets/db_user%'
        password: '%file:/run/secrets/db_password%'
        host: '%file:/run/secrets/db_host%'
```
