### ISSUE TITLE
Feature: Objects.yaml php 8 named arguments

### ISSUE THREAD

**Issue by mhsdesign** [neos/flow-development-collection#2966]
Currently one can only specifiy in the object configuration arguments 1-indexed (which is odd because arent we programmers xD -> there should be an error when you start with 0 btw xD)

but im proposing this:

```yaml
Neos\Neos\Domain\Service\FusionConfigurationCache:
  arguments:
    fooCache:
      object:
        factoryObjectName: Neos\Flow\Cache\CacheManager
        factoryMethodName: getCache
        arguments:
          1:
            value: Neos_Neos_Fusion
    barBum:
      setting: "Neos.Neos:fusion.enableObjectTreeCache"
```

this will currently run into a memory overflow.
Namend arguments are easy and efficiently usable since php 8.0 (no reflection involved ^^)
