### ISSUE TITLE
BUG: Classes are proxied even if they are not target of AOP aspects

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#3060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given some class `SomeDto` with a private constructor:
After a full cache flush, a proxy class is generated even though the class is not actually target of AOP.

When changing the code to trigger a partial cache refresh (in Dev Context) the proxy class is being removed

### Expected Behavior

The proxy class should either *always* or *never* be created – in this case *never* :)

Also, the created proxy code is broken cause it contains:
```
parent::__construct(...$arguments);
```
(related issue: #3059)

### Steps To Reproduce

Create a class

```php
namespace Wwwision\AopTest;

final class SomeDto
{
    private function __construct(
        public readonly string $value,
    ) {}

    public static function fromString(string $value): self {
        return new self($value);
    }
}
```

and a `Policy.yaml` with:

```yaml
privilegeTargets:
  'Neos\Flow\Security\Authorization\Privilege\Method\MethodPrivilege':
    'Wwwision.AopTest:Test':
      matcher: method(Wwwision\AopTest\SomeDto->fromString())
```

the same is true for

```yaml
```yaml
privilegeTargets:
  'Neos\Flow\Security\Authorization\Privilege\Method\MethodPrivilege':
    'Wwwision.AopTest:Test':
      matcher: method(Wwwision\AopTest\SomeDto->nonExistingMethod())
```

### Environment

```markdown
- Flow: 9.0
```
