### ISSUE TITLE
BUG: Authentication is broken with new Proxy Class Building

### ISSUE THREAD

**Issue by bwaidelich** [neos/flow-development-collection#3062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Authenicating (with a session bound auth token) leads to an exception
```
Serialization of 'Closure' is not allowed
```

### Expected Behavior

no exception :)

## 1. Configure an authentication provider (e.g. using the `UsernamePassword` token) with an entry point

for example
```yaml
Neos:
  Flow:
    security:
      authentication:
        providers:
          'Acme.SomePackage:Default':
            provider: PersistedUsernamePasswordProvider
            token: UsernamePassword
            entryPoint: WebRedirect
            entryPointOptions:
              routeValues:
                '@package': Acme.SomePackage
                '@controller': Authentication
                '@action': login
```

## 2. Authenticate

---

Alternatively, the Flow version can be upgraded in a running Neos installation

### Environment

```markdown
- Flow: 9.0-dev
- PHP: 8.2
```

### Anything else?

Slack debugging session: https://neos-project.slack.com/archives/C3MCBK6S2/p1685021294539839
