### ISSUE TITLE
BUG: Static resource collection is published in boot even if it doesn't exists

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#3097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you reset all resource related configuration like this

```
Neos:
  Flow:
    resource:
      collections: []
      storages: []
      targets: []
```

the booting of Flow, still publishes the static collection

`$resourceManager->getCollection(ResourceManager::DEFAULT_STATIC_COLLECTION_NAME)`

without seeing if it gets any collection

### Expected Behavior

Flow should see if there is a actual collection to call publish on

### Steps To Reproduce

Reset resource configuration

```
Neos:
  Flow:
    resource:
      collections: []
      storages: []
      targets: []
```

and start Flow

### Environment

```markdown
- Flow:
- PHP:
```
