### ISSUE TITLE
BUG: Regexvalidator option throws error on apply

### ISSUE THREAD

**Issue by MiauzGenau** [neos/flow-development-collection#3132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I use the `validationErrorMessage` option for the `Neos.Neos/Validation/RegularExpressionValidator` on property, introduced here: https://github.com/neos/neos-ui/pull/2996.

And then try to apply a change to this property, I get an `Unsupported validation option(s) found`-error:
![Screenshot_2023-06-30_at_16 43 10](https://github.com/neos/flow-development-collection/assets/46249106/76dc7589-aa4d-4d15-909f-1cb6472fbade)

### Expected Behavior

I would expect to be able to use this option without issues.

### Steps To Reproduce

Add the validationErrorMessage option to a RegularExpressionValidator, used as a property validator in the yaml NodeType definition.

Example:
```
      validation:
        'Neos.Neos/Validation/RegularExpressionValidator':
          regularExpression: /^(?:http(s)?:\/)?(\/)+[\w\-\.~:\/\?#[\]@!\$&\(\)\*\+=]*$/i
          validationErrorMessage: 'Please enter a valid relative or absolute URL.'
```

Try to apply a change to the property using this validation.
=> Error
