### ISSUE TITLE
BUG: Can't set connection options in PdoBackend

### ISSUE THREAD

**Issue by pagani-BETTERHOMES** [neos/flow-development-collection#3157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In `Neos.Cache/Classes/Backend/PdoBackend.php` you can't set driverOptions like in `Neos.Flow.persistence.backendOptions`.
Therefore no SSL connection can be established like it's required for some hostings.

### Expected Behavior

driverOptions are being recognized and handled like in `Neos.Flow.persistence.backendOptions`

### Steps To Reproduce

**Caches.yaml**

```
Flow_Session_Storage:
  backend: Neos\Cache\Backend\PdoBackend
  backendOptions:
    dataSourceName: 'mysql:host={{DB_HOST}};dbname={{DB_NAME}};charset=utf8mb4'
    username: '{{DB_USER}}'
    password: '{{DB_PASSWORD}}'
    cacheTableName: 'cache_session_storage'
    tagsTableName: 'cache_session_storage_tags'
    driverOptions:
      '%PDO::MYSQL_ATTR_SSL_CA%': 'https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem'
      '%PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT%': false
```

### Environment

```markdown
- Flow:8.3
- PHP:8.2
```
