### ISSUE TITLE
BUG: Configuring FileSystemTarget for localWebDirectoryPersistentResourcesTarget does not work

### ISSUE THREAD

**Issue by kdambekalns** [neos/flow-development-collection#3189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A bit weird, but switching the target for `localWebDirectoryPersistentResourcesTarget` does no longer work… The default settings are for the `FileSystemSimlinkTarget` and include the option `relativeSymlinks`.

That cannot be removed, so changing the target leads to `An unknown option "relativeSymlinks" was specified in the configuration of a resource FileSystemTarget.`

### Expected Behavior

At least unsetting the option (by specifyning `null`) should work!?

### Steps To Reproduce

Add this to a Flow setup:

```yaml
Neos:
  Flow:
    resource:
      targets:
        localWebDirectoryPersistentResourcesTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemTarget'
```

### Environment

```markdown
- Flow: 6.3 and up, I think
- PHP: 7.4, but independent of that
```
