### ISSUE TITLE
Abstaining not possible for entity privilege targets

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#532]
Jira issue originally created by user akii:

``` java
privilegeTargets:
  TYPO3\Flow\Security\Authorization\Privilege\Entity\Doctrine\EntityPrivilege:
    'Some:Privilege':
      matcher: 'isType("Some\Domain\Model")'

    'Some:Privilege.yourOwn'
      matcher: 'isType("Some\Domain\Model") && property("owner") == "context.someService.you"'

...

roles:
  'Some:Normal.User':
    privileges:
      -
        privilegeTarget: 'Some:Privilege.yourOwn'
        permission: GRANT
```

Trying to whitelist `Some\Domain\Model` will fail because abstaining for `Some:Privilege` does not work.

 Jira-URL: https://jira.neos.io/browse/FLOW-357

**Comment by bwaidelich** [comment]
I looked into this one again because I stumbled upon it myself, and I think this is a limitation of the underlying Doctrine filter API..
To achieve what you described you'll have to create a custom privilege or do something like this:
```yaml
privilegeTargets:
  TYPO3\Flow\Security\Authorization\Privilege\Entity\Doctrine\EntityPrivilege:
    'Some:Privilege.foreign':
      matcher: 'isType("Some\Domain\Model") && property("owner") != "context.someService.you"'

    'Some:Privilege.yourOwn'
      matcher: 'isType("Some\Domain\Model") && property("owner") == "context.someService.you"'
```
because `EntityPrivilege`s don't have a weight currently.
