### ISSUE TITLE
Extending array values in settings with anonymous keys ("-") is not safe

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#555]
Jira issue originally created by user @hlubek:

It is not safe to add an entry to an array setting by using "-" for the key, e.g.:

```
    persistence:
      doctrine:
        eventListeners:
          -
            events: ['postPersist', 'postUpdate', 'postRemove']
            listener: 'TYPO3\Neos\Domain\EventListener\AccountPostEventListener'
```

If a second package does the same, this will end up in only one event listener, which will be overridden by the second one. This happened at least with the phpyaml extension being used to parse YAML files.

 Jira-URL: https://jira.neos.io/browse/FLOW-22
