### ISSUE TITLE
If a parent role is added and then removed in Policy.yaml the connection is not removed from the database

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#577]
Jira issue originally created by user david.sporer:

I've just accidentially added a parent role to another role and removed it afterwards.
After that I've discovered that the connection was still in place.
Imagine the following:

``` yaml
roles:
  Administrator: {  }
  NormalUser: {  }
```

I've changed that to:

``` yaml
roles:
  Administrator: [ 'NormalUser' ]
  NormalUser: {  }
```

And then back to the first version.
There's one property where access is granted for the Administrator and denied for the NormalUser role. After I've changed the definition back to the first version access to that property was still denied for accounts that had the Administrator role.

The reason seems to be that the connection between the two roles was not removed from the table typo3_flow_security_policy_role_parentroles_join. In this table NormalUser is still the parent role of Administrator. If I delete that entry everything worked again as expected.

 Jira-URL: https://jira.neos.io/browse/FLOW-318
