### ISSUE TITLE
Allow overriding of privilege parameters from the account model

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#593]
Jira issue originally created by user @bwaidelich:
## Current situation:

[Privilege Parameters](http://flowframework.readthedocs.org/en/3.0/TheDefinitiveGuide/PartIII/Security.html#using-privilege-parameters) allow to use placeholders in privilege matchers:

``` yaml
privilegeTargets:

  'TYPO3\Flow\Security\Authorization\Privilege\Method\MethodPrivilege':

    'Acme.SomePackage:Foo':
      matcher: 'method(Acme\SomePackage\Controller\SecureController->{parameters.action}Action())'
      parameters:
        'action':
          className: 'TYPO3\Flow\Security\Authorization\Privilege\Parameter\StringPrivilegeParameter'
```

The parameters have to be specified when assigning a role to a PrivilegeTarget:

``` yaml
roles:
  'Acme.SomePackage:SomeRole':
    privileges:
      -
        privilegeTarget: 'Acme.SomePackage:Foo'
        parameters:
          'action': 'secure'
        permission: GRANT
```

Otherwise an exception would be triggered:

```
#1355480641: Error for privilegeTarget "Acme.SomePackage:Foo" in Role "Acme.SomePackage:SomeRole": The parameter "action" is not specified
```

So parameters have to be specified at _design time_ which drastically limits their practicability
## Suggestion

Instead of replacing the parameter placeholders during parsing of the `Policy.yaml` already we suggest to _defer_ that to when a `Role` is assigned to the `Account` in `PolicyService::initialize()`.

That would allow for specifying/overriding parameter values **in the Account model\* itself which in turn would make it possible to implement some kind of _Group_ mechanism on top of the existing *Role**-based authorization.
### Example:

Imagine you have a role **NewsEditor** but you want to limit editors to certain news _categories_, too.
Now you could create a sub-role for for every category in question (like **NewsEditor.Marketing*, *NewsEditor.Community**, ...) but that's tedious and news categories can change during _runtime_.

By using deferred parameters you could solve this with the one existing role and parameters in the `Account`<->`Role` assignment: "Account XYZ has role _NewsEditor_ with a parameter _categories_ of _marketing, community_".
### Consequences
- The `Account` Model has to be extended, so that the `Account`<->`Role` relation contains (optional) parameter values
  ***\* The service classes (e.g. `AccountFactory`) & CLI commands have to be adjusted accordingly so that one can specify parameters
  ***\* In order to be used from Neos the users management module should be extended
- If you try to assign a role to an account without specifying all required parameters, an exception needs to be thrown
- The `Security\Context::contextHash` that is currently used to cache all kinds of data based only on the authenticated roles has to be extended to include _parameters_, too
- Matchers for the `MethodPrivilege` that contain parameter placeholders have to be rewritten because they are serialized at _compile time_
  
  Jira-URL: https://jira.neos.io/browse/FLOW-386
