### ISSUE TITLE
Broken paths for links created below Web/_Resources/Static/Packages/

### ISSUE THREAD

**Issue by neos-bot** [neos/flow-development-collection#633]
Jira issue originally created by user jrenggli:

Reporter: Morton Jonuschat

When using PHP in a chroot environment (php-fpm + chroot) the „detected“ absolute paths don't match the paths seen by the webserver when serving static assets.

Pre-Requisites:

1) The following directory holds the TYPO3 Neos 1.0 installation: /srv/customers/webs/user1/html/domain1.de/
2) The apache vhost ist configured with a document root: /srv/customers/webs/user1/html/domain1.de/Web/
3) PHP is chrooted to: /srv/customers/webs/user1/

What happens is that Neos/Flow publishes the static resources and creates absolute symlinks pointing to /html/domain1.de/.../, for example TYPO3.Flow -> /html/domain1.de/Packages/Framework/TYPO3.Flow/Resources/Public

These links are correct from the viewpoint of the PHP client but are wrong from the viewpoint of the Webserver. The correct symlink should be relative so that both PHP and Apache can reach the right destination independent of their starting point.
TYPO3.Flow -> ../../../../Packages/Framework/TYPO3.Flow/Resources/Public

 Jira-URL: https://jira.neos.io/browse/FLOW-81

**Comment by RafaelKa** [comment]
This can be closed. 

Fixed in [#187](https://github.com/neos/flow-development-collection/pull/187)

use 
```
TYPO3:
  Flow:
    resource:
      targets:
        localWebDirectoryStaticResourcesTarget:
          targetOptions:
            relativeSymlinks: true
        localWebDirectoryPersistentResourcesTarget:
          targetOptions:
            relativeSymlinks: true
```
