### ISSUE TITLE
Missing "Schema"-property in "TYPO3.Flow.security.schema.yaml" for "token"-property

### ISSUE THREAD

**Issue by dnepro** [neos/flow-development-collection#700]
On running "flow configuration:validate" i receive an error, stating that: 
```yaml
- Settings.TYPO3.Flow.security.authentication.providers.Flowpack.Neos.FrontendLogin:Frontend.token -> This property is not allowed here, check the spelling if you think it belongs here.
```
This is due to this "Settings"-configuration:
```yaml
TYPO3:
  Flow:
    security:
      authentication:
        providers:
          'Flowpack.Neos.FrontendLogin:Frontend':
            provider: 'X\Y\FrontendLogin\Authentication\Provider\PersistedUsernamePasswordWlkidProvider'
            token: 'X\Y\FrontendLogin\Authentication\Token\UsernamePasswordWlkid'
            requestPatterns:
              'Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern': 'frontend'
```
While for me this is completely valid and functional and can be found in the [documentation](http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Security.html#reuse-of-tokens-and-providers).

And after asking on the [Flow Slack Channel](https://neos-project.slack.com/archives/flow-general/p1478621434002367) i would like to create a PR, adding:

```yaml
  'authentication':
    properties:
      'providers':
        additionalProperties:
          properties:
            'token': { type: string }
```
If this is a valid PR i would just like to know against which branch to do the PR, master?
