### ISSUE TITLE
Cannot publish Static Resources using FileSystemTarget

### ISSUE THREAD

**Issue by maltemuth** [neos/flow-development-collection#871]
### Description

When selecting the FileSystemTarget for localWebDirectoryStaticResourcesTarget, the command
`./flow resource:publish --collection static` throws an exception.
### Steps to Reproduce

1. Install Flow
2. Add configuration to Configuration/Settings.yaml inside Neos.Flow:
```
resource:
      targets:
        localWebDirectoryStaticResourcesTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemTarget'
          targetOptions:
            path: '%FLOW_PATH_WEB%_Resources/Static/'
            baseUri: '_Resources/Static/'
```
3. Run `./flow resource:publish --collection static`

#### Expected behavior

The file Web/_Resources/Static/Neos.Welcome is directory (containing Styles/styles.css)

#### Actual behavior

Exception:
```
Neos\Flow\Error\Exception (Exception code: 1)
Warning: array_merge(): Argument #2 is not an array in /var/www/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_ResourceManagement_Collection.php line 162
```

### Affected Versions
Flow: 4.0.1
without proper testing so far:
3.2, 3.3

### Further Information

The call to PackageStorage::getObjectsByPathPattern indeed returns a Generator instead of an array. Converting this Generator using `iterator_to_array` fixes the problem.
