### ISSUE TITLE
Not using FQN of token in authentication causes exception

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-development-collection#947]
### Description

Given the following configuration
```
Neos:
  Flow:
    security:
      authentication:
        providers:
          'Vendor.App:User':
            provider: 'PersistedUsernamePasswordProvider'
            token: 'UsernamePassword'
```

Throws the following exception
```
Call to a member function setAuthenticationEntryPoint() on null

Type: Error
File: Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Securit
y_Authentication_AuthenticationProviderManager.php
Line: 383

Exception Code	1355480641
Exception Type	Neos\Flow\Core\Booting\Exception\SubProcessException
Log Reference	2017041620534868df6b
Thrown in File	Packages/Framework/Neos.Flow/Classes/Core/Booting/Scripts.php
Line	632
```

Adjusting to  `token: 'Neos\Flow\Security\Authentication\Token\UsernamePassword'` makes the resolving return the correct token object

### Steps to Reproduce

1. Set `token: 'UsernamePassword'` in a authentication provider configuration
2. Reload page managed by the provuder (for example via a `requestPatterns`
3. See it throw the exception :-)

#### Expected behavior

Resolve the object, similar to it resolving `provider` via a shortname

#### Actual behavior

Throws exception (see above)

### Affected Versions

Flow: Developing `"neos/flow": "4.0.1"` and also in 4.0.0. Dunno about earlier versions
